//LANGUAGE
export const SET_CURRENT_LANG = 'SET_CURRENT_LANG';
export const GET_CURRENT_LANG = 'GET_CURRENT_LANG';

//LOADER
export const SHOW_LOADER = 'SHOW_LOADER';
export const HIDE_LOADER = 'HIDE_LOADER';

//SEARCH FOR A PHOTO
export const SEARCH_PHOTOS_RECIEVE = 'SEARCH_PHOTOS_RECIEVE';
export const SEARCH_PHOTOS_REQUEST = 'SEARCH_PHOTOS_REQUEST';


//DOWNLOAD A PHOTO
export const DOWNLOAD_A_PHOTO_REQUEST = 'DOWNLOAD_A_PHOTO_REQUEST';
export const DOWNLOAD_A_PHOTO_RECIEVE = 'DOWNLOAD_A_PHOTO_RECIEVE';

//FEATURED COLLECTIONS

export const PHOTOGRAPHER_PROFILE_REQUEST = 'FEATURED_COLLECTIONS_REQUEST';
export const PHOTOGRAPHER_PROFILE_RECIEVE = 'FEATURED_COLLECTIONS_RECIEVE';